INSERT INTO PUBLIC.MPA (NAME) VALUES ('G');
INSERT INTO PUBLIC.MPA (NAME) VALUES ('PG');
INSERT INTO PUBLIC.MPA (NAME) VALUES ('PG-13');
INSERT INTO PUBLIC.MPA (NAME) VALUES ('R');
INSERT INTO PUBLIC.MPA (NAME) VALUES ('NC-17');

INSERT INTO PUBLIC.GENRES (NAME) VALUES ('Комедия');
INSERT INTO PUBLIC.GENRES (NAME) VALUES ('Драма');
INSERT INTO PUBLIC.GENRES (NAME) VALUES ('Мультфильм');
INSERT INTO PUBLIC.GENRES (NAME) VALUES ('Триллер');
INSERT INTO PUBLIC.GENRES (NAME) VALUES ('Документальный');
INSERT INTO PUBLIC.GENRES (NAME) VALUES ('Боевик');